name: Test and Build

on:
  push:
    branches:
      - main
    paths:
      - "**/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      # Lint the code
      - name: Run flake8 lint
        run: |
          flake8 --ignore=E501,F401 .

      # Login to DockerHub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Generate dynamic version tag
      - name: Generate image tag
        id: version
        run: echo "version=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build . -t swbanerjee/demo-app:${{ env.version }}

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push swbanerjee/demo-app:${{ env.version }}

      # Update K8s manifest
      - name: Update K8s Manifests
        run: |
          sed -i "s|image: swbanerjee/demo-app:.*|image: swbanerjee/demo-app:${{ env.version }}|g" deploy/deploy.yaml
          cat deploy/deploy.yaml

      # Commit and push updated manifest
      - name: Commit updated manifest
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git add deploy/deploy.yaml
          git commit -m "Update deploy.yaml with new image version - ${{ env.version }}" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Swagata-ux/Flask-app-Argo-CD.git
          git push origin main
