name: Test and Build

on:
  push:
    branches:
      - main
    paths:
      - "**/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setting up environment
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      # Run Linting tests
      - name: Run flake8 lint
        run: |
          flake8 --ignore=E501,F401 .

      # DockerHub Login
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Generate dynamic version tag
      - name: Generate image tag
        id: version
        run: echo "version=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build . -t swbanerjee/demo-app:${{ env.version }}

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push swbanerjee/demo-app:${{ env.version }}
      # Update the K8s Manifest Files
      - name: Update K8s Manifests
        run: |
          cat deploy/deploy.yaml
          sed -i "s|image: swbanerjee/demo-app:.*|image: swbanerjee/demo-app:${{ env.VERSION }}|g " deploy/deploy.yaml
          cat deploy/deploy.yaml

      # Update Github
      - name: Commit the changes
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions Bot"
          git add deploy/deploy.yaml
          git commit -m "Update deploy.yaml with new image version - ${{ env.VERSION }}"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com:Swagata-ux/Flask-app-Argo-CD.git
          git push origin master
